# doxygen-deploy.yml
name: doxygen-deploy

on:
  push:
    branches: [ master ]  # set to your default branch (master in your case)

jobs:
  deploy-worksheet5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doxygen
        run: sudo apt-get install -y doxygen

      - name: Run Doxygen
        working-directory: ${{ github.workspace }}/worksheet5
        run: doxygen

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: ${{ github.workspace }}/worksheet5/html
